"""removed the github and google id

Revision ID: f35b2fee0d91
Revises: 308cc30e877a
Create Date: 2025-02-25 09:58:43.464729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35b2fee0d91'
down_revision = '308cc30e877a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('github_id')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('github_id', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
